<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>DynamicMaps</AssemblyName>
    <Description>Dynamic in-game maps for SPT</Description>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup>
    <TarkovDir Condition=" '$(TarkovDir)' == '' ">D:\SPT 4.0.0 DEV\</TarkovDir>
    <TarkovPluginsSPTDir>$(TarkovDir)BepInEx\plugins\spt\</TarkovPluginsSPTDir>
    <TarkovManagedDir>$(TarkovDir)EscapeFromTarkov_Data\Managed\</TarkovManagedDir>
    <TarkovBepInExCoreDir>$(TarkovDir)BepInEx\core\</TarkovBepInExCoreDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack.MSBuild.Task" Version="2.0.34.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(TarkovManagedDir)Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(TarkovManagedDir)Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Comfort.Unity">
      <HintPath>$(TarkovManagedDir)Comfort.Unity.dll</HintPath>
    </Reference>
    <Reference Include="DissonanceVoip">
      <HintPath>$(TarkovManagedDir)DissonanceVoip.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>$(TarkovManagedDir)DOTween.dll</HintPath>
    </Reference>
    <Reference Include="DOTween.Modules">
      <HintPath>$(TarkovManagedDir)DOTween.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(TarkovManagedDir)Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(TarkovManagedDir)Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(TarkovManagedDir)Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(TarkovManagedDir)UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(TarkovManagedDir)UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.UIModule.dll</HintPath>
    </Reference>
      <Reference Include="Unity.VectorGraphics">
          <HintPath>$(TarkovManagedDir)Unity.VectorGraphics.dll</HintPath>
          <Private>true</Private>
      </Reference>
      <Reference Include="Unity.InternalAPIEngineBridge.003">
          <HintPath>$(TarkovManagedDir)Unity.InternalAPIEngineBridge.003.dll</HintPath>
          <Private>true</Private>
      </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(TarkovBepInExCoreDir)0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepinEx">
      <HintPath>$(TarkovBepInExCoreDir)BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepinEx.Preloader">
      <HintPath>$(TarkovBepInExCoreDir)BepInEx.Preloader.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>$(TarkovPluginsSPTDir)spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="spt-custom">
      <HintPath>$(TarkovPluginsSPTDir)spt-custom.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>$(TarkovPluginsSPTDir)spt-common.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- Gets the version property from the VERSION.txt file -->
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <VersionFile Include="VERSION.txt" />
      <VersionCs Include="$(ProjectDir)Version.cs" />
      <Compile Include="@(VersionCs)" Exclude="@(VersionCs)" /> <!-- Resolves double include -->
      <FileWrites Include="@(VersionCs)" />
    </ItemGroup>

    <ReadLinesFromFile File="@(VersionFile)">
      <Output TaskParameter="Lines" PropertyName="Version" />
    </ReadLinesFromFile>

    <!-- Write the version to Version.cs, kind of a hack to get version info into BepInEx -->
    <WriteLinesToFile File="@(VersionCs)" Overwrite="true" Lines="// HACK: autogenerated file containing version info from VERSION.txt" />
    <WriteLinesToFile File="@(VersionCs)" Lines="namespace DynamicMaps{public static class BuildInfo {public const string Version = &quot;$(Version)&quot;%3B}}" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
        <AssembliesToMerge Include="$(ProjectDir)$(OutDir)Unity.VectorGraphics.dll" />
        <AssembliesToMerge Include="$(ProjectDir)$(OutDir)Unity.InternalAPIEngineBridge.003.dll" />
        <ServerComponents Include="$(ProjectDir)../Server/bin/Release/mpstark-dynamicmaps/*.*" />
        <OutputDLL Include="$(ProjectDir)$(OutDir)$(TargetName).dll" />
        <License Include="$(ProjectDir)LICENSE" />
        <Resources Include="$(ProjectDir)Resources\**\*.*" />
    </ItemGroup>

    <!-- Merge Unity.VectorGraphics and Unity.InternalAPIEngineBridge.003 into the output DLL -->
    <ILRepack
      ExcludeFileTokPatterns=""
      KeyFile=""
      LogFile=""
      Parallel="true"
      AttributeFile=""
      OutputFile="$(ProjectDir)$(OutDir)$(TargetName).dll"
      PrimaryAssemblyFile="$(ProjectDir)$(OutDir)$(TargetName).dll"
      AssemblyFiles="@(AssembliesToMerge)"
      TargetKind="SameAsPrimaryAssembly"
      XmlDocumentation="false"
      AllowDuplicateResources="false"
      Internalize="true"
    />

    <!-- Copies the output and resources to tarkov game folder -->
      <Copy SourceFiles="@(OutputDLL);@(Resources);@(License)" DestinationFolder="$(TarkovDir)BepInEx\plugins\DynamicMaps\%(RecursiveDir)" />
      <Copy SourceFiles="@(ServerComponents)" DestinationFolder="$(TarkovDir)SPT\user\mods\mpstark-dynamicmaps\%(RecursiveDir)" />

    <!-- Creates a release zip file -->
    <RemoveDir Directories="$(ProjectDir)release" />
      <Copy SourceFiles="@(OutputDLL);@(Resources);@(License)" DestinationFolder="$(ProjectDir)release\DynamicMaps\BepInEx\plugins\DynamicMaps\%(RecursiveDir)" />
      <Copy SourceFiles="@(ServerComponents)" DestinationFolder="$(ProjectDir)release\DynamicMaps\SPT\user\mods\mpstark-dynamicmaps\%(RecursiveDir)" />
    <ZipDirectory SourceDirectory="$(ProjectDir)release\DynamicMaps\" DestinationFile="$(ProjectDir)release\DynamicMaps-$(Version).zip" />
  </Target>

</Project>
